# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63e881565150d071d4eca61534db353c958305323664f91d7c1887c30bdbc0c081cf41211f39b924c1ae645e99301a812c4fda7fe62a0f4f3afa1207ed0bd5f4

test:
  secret_key_base: 6b759618ed95ca2002ead542cc4a4723c5882cd271dae69030fd320a4515ef84a4e97dc8c86ae517ea836bbeedc791f56545bc082525c334970455c968c38969

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
