# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b3d4972a4fe2cd8bbcb00bed33b7fe89edf09d125157dd27471dddaffc4dbbd4dc6ef3d54a97be77b34c367233cf0019e30a81f87833e3bf7d61f23c034c623

test:
  secret_key_base: a7da3cac1d7e18c477bbdd107f3c229443eb64b2ddd02ebd165a5e6a2e4ca4e43b9af318d3842304df8a2e96bdfbd9e731b9d424da278d5d0b1142dd7ebcb2de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
